[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8787/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "ws://localhost:8787/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


